name: Windows 10 RDP

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: windows-latest

    steps:
      - name: Downloading & Installing Essentials
        run: |
          Invoke-WebRequest -Uri "https://clicker-games.netlify.app/WindowsRDP_files/Downloads.bat" -OutFile "Downloads.bat"
          cmd /c Downloads.bat

      - name: Adding support files and folder
        run: cmd /c support.bat

      - name: RDP Message Sent
        run: |
          echo "Starting RDP webhook notification..."
          python Rdp_webhook.py
          echo "RDP notification sent successfully."

      - name: Log In To RustDesk
        run: cmd /c show.bat

      - name: Start Winver
        run: cmd /c winver

      - name: CPU Checker
        run: |
          echo "Starting CPU Checker..."
          python time.py
          echo "CPU check completed."
